### PR TITLE
README: Add warning

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by kanzure** [comment]
Not going to merge this. The description of the repository already links to the other repository, and the issues tracker has been disabled for some time now. Also, I have pushed latest upstream to the master branch.

**Comment by mathiasbynens** [comment]
> Also, I have pushed latest upstream to the master branch.

That only makes the difference less obvious IMHO. If https://github.com/iimarckus/pokered is the canonical repo nowadays, that fact could be made clearer.

**Comment by mathiasbynens** [comment]
@kanzure Btw, you can ask GitHub Support to mark iimarckus/pokered as the root/upstream repository and https://github.com/kanzure/pokered as its fork instead of the other way around — they’re happy to make changes like that.

That would reduce confusion as well IMHO.

To do this, just email support@github.com asking the following:

> Could you please mark https://github.com/iimarckus/pokered as the root repository and https://github.com/kanzure/pokered as its fork instead of the other way around?

**Comment by kanzure** [comment]
request sent

**Pull request closed without merging**
